# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.hostname = "node2.xtl"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "node2.xtl"
     vb.cpus = 1
     vb.memory = "2048"
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt install docker.io
    ## set a password for root user
    #sudo passwd root
    
    ## Allow login by user 
    # vi /etc/ssh/sshd_config
    # PermitRootLogin yes
    # PasswordAuthentication yes
    # ChallengeResponseAuthentication yes    
    # systemctl restart ssh


    


  SHELL
end
